### ISSUE TITLE
Slide up and down icons showing at the same time

### ISSUE THREAD

**Issue by Shivansh175** [miroslavpejic85/mirotalkwebrtc#4]
When freshly visiting the page client.html both the icons( Slide up and slide down ) were showing up simultaneously which i think is a bug. however it sorts out when any of them is clicked but on refreshing the page same issue arises again n again.

![Screenshot 2023-10-05 150648](https://github.com/miroslavpejic85/mirotalkwebrtc/assets/112273961/fb7ba7da-7250-40f7-ada2-39e454b65103)

I think i can fix it...so please assign me this issue.

**Comment by miroslavpejic85** [comment]
Hey @Shivansh175!

You right, let's summarize the issue and solution briefly:

**Security**: We currently save the Token and UserId in the `sessionStorage` as is generally considered more secure for storing sensitive data because it has a more limited scope and is less susceptible to XSS attacks.

**Issue:** When users paste a copied dashboard URL into a new tab, they encounter a `401 Unauthorized` error, and the page doesn't load correctly.

**Solution:** The code in `client.js` now fetches configuration data using `getConfig()`. If successful, it loads the configuration, tooltips, and user roles. If there's an error (e.g., unauthorized), it redirects the user to the home page.

Here the snippet:

```js
$(document).ready(async function () {
    elemDisplay(showBoxesDS, false); // ---> quick fix.

    // Best fix
    getConfig()
        .then((cfg) => {
            // User from same session
            loadConfig(cfg);
            loadToolTip(toolTips);
            handleUserRoles();
        })
        .catch((err) => {
            // User not from same session, redirect to home.
            openURL('/');
        });
});

function loadConfig(cfg) {
    config = cfg;
    console.log('Config', config);
    // ....
```

**Comment by Shivansh175** [comment]
i couldn't absorb that much at one go
can u please describe me what i've to do in easy words..?
will u assign me the issue or i've to start working on it without getting it assigned?

**Comment by miroslavpejic85** [comment]
In `frontend/client.js` change the logic as the follow:

<br>

<img width="789" alt="mirotalk-web-fix" src="https://github.com/miroslavpejic85/mirotalkwebrtc/assets/70838434/87061bf5-85f5-4cbf-accb-735e09ae6d67">
